openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/thanakijwanavit/villaInventory/1.0.0
info:
  version: "1.0.0"
  title: Sample Access Code Flow OAuth2 Project
  description: >-
    This is an example of using OAuth2 Access Code Flow in a specification to
    describe security to your API.
security:
  - accessCode:
      - read
      - write
paths:
  /presign:
    post:
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Presign'
      summary: Presign to upload to s3
      description: >-
        get presigned data to upload to s3
      responses:
        '200':
          description: success
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/PresignedResponse'
        '400':
          description: failed
  /ingest:
    post:
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#ingest.yaml/Ingest'
      summary: Server example operation
      description: >-
        ingest the data which is uploaded to s3 
      responses:
        '200':
          description: success
        '400':
          description: failed
  /ping:
    get:
      summary: Server heartbeat operation
      description: >-
        This operation shows how to override the global security defined above,
        as we want to open it up for all users.
      security: []
      responses:
        '200':
          description: OK
components:
  schemas:
    PresignedResponse:
      type: object
      properties:
        fields:
          properties:
            AWSAccessKeyId:
              type: string
            key:
              type: string
            policy:
              type: string
            signature:
              type: string
          required:
          - AWSAccessKeyId
          - key
          - policy
          - signature
          type: object
        url:
          type: string
      required:
      - fields
      - url
    Presign:
      type: object
      properties:
        key:
          type: string
      required: 
        - key
  securitySchemes:
    accessCode:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: 'http://example.com/oauth/auth'
          tokenUrl: 'http://example.com/oauth/token'
          scopes:
            write: allows modifying resources
            read: allows reading resources