$schema: http://json-schema.org/schema#
properties:
  SaleMode_unit:
    type: string
  ba_nprice:
    type: string
  content_en:
    type: string
  content_th:
    type: string
  cprcode:
    type: integer
  hema_brand_en:
    type: string
  hema_brand_th:
    type: string
  hema_name_en:
    type: string
  hema_name_th:
    type: string
  hema_sizedesc:
    type: string
  iprcode:
    type: integer
  master_online:
    type: string
  online_category_l1_en:
    type: string
  online_category_l1_th:
    type: string
  online_category_l2_en:
    type: string
  online_category_l2_th:
    type: string
  online_category_l3_en:
    type: string
  online_category_l3_th:
    type: string
  oprcode:
    type: integer
  ordertype:
    type: string
  pr_abb:
    type: string
  pr_active:
    type: string
  pr_barcode:
    type: integer
  pr_barcode2:
    type: integer
  pr_brand_en:
    type: string
  pr_brand_th:
    type: string
  pr_cgcode:
    type: string
  pr_code:
    type: string
  pr_country_en:
    type: string
  pr_country_th:
    type: string
  pr_dpcode:
    type: string
  pr_engname:
    type: string
  pr_filter_en:
    type: string
  pr_filter_th:
    type: string
  pr_ggcode:
    type: string
  pr_keyword_en:
    type: string
  pr_keyword_th:
    type: string
  pr_market:
    type: string
  pr_name:
    type: string
  pr_name_en:
    type: string
  pr_name_th:
    type: string
  pr_online_name_en:
    type: string
  pr_online_name_th:
    type: string
  pr_puqty:
    type: string
  pr_sa_method:
    type: string
  pr_sucode1:
    type: string
  pr_suref3:
    type: string
  prtype:
    type: string
  psqty:
    type: string
  pstype:
    type: string
  sort_villa_sku:
    type: integer
  sort_weight:
    type: string
  villa_category_l1_en:
    type: string
  villa_category_l2_en:
    type: string
  villa_category_l3_en:
    type: string
  villa_category_l4_en:
    type: string
required:
- SaleMode_unit
- ba_nprice
- content_en
- content_th
- cprcode
- hema_brand_en
- hema_brand_th
- hema_name_en
- hema_name_th
- hema_sizedesc
- iprcode
- master_online
- online_category_l1_en
- online_category_l1_th
- online_category_l2_en
- online_category_l2_th
- online_category_l3_en
- online_category_l3_th
- oprcode
- ordertype
- pr_abb
- pr_active
- pr_barcode
- pr_barcode2
- pr_brand_en
- pr_brand_th
- pr_cgcode
- pr_code
- pr_country_en
- pr_country_th
- pr_dpcode
- pr_engname
- pr_filter_en
- pr_filter_th
- pr_ggcode
- pr_keyword_en
- pr_keyword_th
- pr_market
- pr_name
- pr_name_en
- pr_name_th
- pr_online_name_en
- pr_online_name_th
- pr_puqty
- pr_sa_method
- pr_sucode1
- pr_suref3
- prtype
- psqty
- pstype
- sort_villa_sku
- sort_weight
- villa_category_l1_en
- villa_category_l2_en
- villa_category_l3_en
- villa_category_l4_en
- test
type: object