# DO NOT CHANGE FILE NAME

specialOfferRootGroup:
  id: 9000000003
  name: Special Offer

preorderRootGroup:
  id: 38153
  name: Pre Order

ignoreGroupList:
  - id: 123456789

paymentMethods:
  - name: "Credit/Debit Card"
    img: ["visa.svg", "master-card.svg", "jcb.svg"]
  - name: "Amex"
    img: ["amex.svg"]
#   - name: "Vplus Wallet"
#     img: ["wallet-logo.svg"]
  - name: "Other"
    img: ["thai_qr.png","alipay_logo.jpg", "wechat-pay.svg", "union.svg"]
